const API_KEY = "cc1ad33339b6426ba90ec29a7f60e64e";
const url = "https://newsapi.org/v2/everything?q=";

window.addEventListener("load", () => fetchNews("India"));

function reload() {
    window.location.reload(); //reload the website to its home page
}

async function fetchNews(query) {
    const res = await fetch(`${url}${query}&apiKey=${API_KEY}`);  // fetching the news with the string generated by this 
    const data = await res.json();   //gives all the news data in json format from different channels and authors
    bindData(data.articles);  // bind the data of a particular article for single card
}

function bindData(articles) {
    const cardsContainer = document.getElementById("cards-container");
    const newsCardTemplate = document.getElementById("template-news-card");

    cardsContainer.innerHTML = "";  // innerHTML should be empty whenever we call for news related to some topic

    articles.forEach((article) => {
        if(!article.urlToImage) return; //show news with images only
        const cardClone = newsCardTemplate.content.cloneNode(true);  //Clone/Copy all the html inside the templete tag 
        fillDataInCard(cardClone, article);  // sets the default cards with the real news data on web page
        cardsContainer.appendChild(cardClone);  //create the change in html in the webpage
    });
}

function fillDataInCard(cardClone, article) {  //setting the news data in the html cards
    const newsImg = cardClone.querySelector('#news-img');
    const newsTitle = cardClone.querySelector('#news-title');
    const newsSource = cardClone.querySelector('#news-source');
    const newsDesc = cardClone.querySelector('#news-desc');

    newsImg.src = article.urlToImage;
    newsTitle.innerHTML = article.title;
    newsDesc.innerHTML = article.description;

    const date = new Date(article.publishedAt).toLocaleString("en-US", {
        timeZone: "Asia/Jakarta",
    })

    newsSource.innerHTML = `${article.source.name} - ${date}`;

    cardClone.firstElementChild.addEventListener("click", () => {
        window.open(article.url, "_blank");
    });
}

let curSelectedNav = null;
function onNavItemClick(id) {
    fetchNews(id);
    const navItem = document.getElementById(id);
    curSelectedNav?.classList.remove('active');  //remove the previous active state nav bar topic
    curSelectedNav = navItem;  
    curSelectedNav.classList.add('active'); // set current select topic from nav bar active
}

const searchButton = document.getElementById('search-button');
const searchText = document.getElementById('search-text');

searchButton.addEventListener('click', () => {   // searching for news related to text entered in search bar
    const query = searchText.value;
    if(!query) return;
    fetchNews(query);
    curSelectedNav?.classList.remove('active');
    curSelectedNav = null;
});